# Generated by Django 5.1.1 on 2024-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds_avail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('Government', 'government'), ('Private', 'private')], max_length=255),
        ),
    ]
